### ISSUE TITLE
title attribute if truncated

### ISSUE THREAD

**Issue by samwalshnz** [parsable/react-truncate-markup#13]
Before I look into creating a solution, I was wondering if you would be open to having a boolean prop called something like `withTitle` (open to naming suggestions). If the prop is set (to true), then when the content inside the element is truncated, it sets the `title` attribute to the original text.

The purpose of this is so that when text is truncated, you can still hover over the text to see the original text in the browser-default tooltip.

Thoughts?

**Comment by samwalshnz** [comment]
Alternatively, if we had the onAfterTruncate callback (https://github.com/parsable/react-truncate-markup/issues/11) then we could just hook into this instead.

**Comment by samwalshnz** [comment]
Also, I suppose it would need to use something similar to https://github.com/kevinzwhuang/react-to-string in order to convert the markup into a plain string to be used in the `title` attribute.

**Comment by patrik-piskay** [comment]
Hey @samwalshnz, thanks for the suggestion! I'll definitely plan to implement something like `onAfterTruncate` and I'd prefer that to be the solution for your case.

I should have time to address this soon (along with other reported issues), next week 🤞

**Comment by samwalshnz** [comment]
`onAfterTruncate` sounds great. Happy for this to be closed. Thanks @patrik-piskay

**Comment by patrik-piskay** [comment]
Let's continue the discussion in https://github.com/parsable/react-truncate-markup/issues/11
