### ISSUE TITLE
Provide mechanism to accept markup as string

### ISSUE THREAD

**Issue by pauloamgomes** [parsable/react-truncate-markup#19]
It would be interesting if we can pass markup via string (e.g. the child element using dangerouslySetInnerHTML)

**Comment by patrik-piskay** [comment]
That won't be possible as `TruncateMarkup` takes advantage of the react elements tree structure. We would need to convert the html string into a tree of React Elements, but that could be done on the consumer's side as well, using something like [react-html-parser](https://github.com/wrakky/react-html-parser).

I imagine this should work:
```jsx
const html = '<div>Example HTML string</div>';
return (
  <TruncateMarkup>
    <div>{ ReactHtmlParser(html) }</div>
  </TruncateMarkup>
);
```

**Comment by pauloamgomes** [comment]
Thanks, I'm using htmr for that and it works with one issue:
I'm aware that can only have default dom elements, but do you think it's possible to have react custom ones? I need to have Link (reach router) elements instead of standard html links

**Comment by patrik-piskay** [comment]
Unfortunately that's not possible (see https://github.com/parsable/react-truncate-markup/issues/12#issuecomment-444761758 for a more in-depth explanation). 

When we allow custom React components, they won't be truncated -> either the whole custom component fits and renders, or it doesn't (even by one character) and the whole custom component's content is truncated from the original content.

Would that be something you'd be interested in? An opt-in option where you can allow custom react components to be used with this one caveat (that the whole custom component content might get stripped if any part of that content doesn't fit)?

**Comment by pauloamgomes** [comment]
Hi @patrik-piskay , many thanks for your detailed explanation, I understand the issue. And yes, believe that having that (with the mentioned caveat) will still be a nice feature.

**Comment by bonesoul** [comment]
react-html-parser seems to be outdated, any alternatives?

**Comment by ponnexcodev** [comment]
@bonesoul [html-react-parser](https://github.com/remarkablemark/html-react-parser) seems to work for me
