### ISSUE TITLE
onAfterTruncate missing from TruncateProps in index.d.ts

### ISSUE THREAD

**Issue by subs1da** [parsable/react-truncate-markup#20]
The index.d.ts file has not been updated with the new onAfterTruncate property (which causes warnings when using the library from TypeScript)

https://github.com/parsable/react-truncate-markup/blob/488698a3234e9a828e2e1b0d63b7ae8c25ab6b87/index.d.ts#L3

(May I also say, not that it matters, onAfterTruncate is a really odd name :) onTruncate would have been a bit more concise)

**Comment by patrik-piskay** [comment]
huh, now that you mention it, you're probably right 😅 

regarding the ts definitions, would you like sending a PR that updates it?
