### ISSUE TITLE
Fails in Firefox

### ISSUE THREAD

**Issue by constantinpojoga** [parsable/react-truncate-markup#23]
I'm developing a React extension and using "react-truncate-markup" to truncate the html from the api. Works fine in Chrome and does exactly what I need, but unfortunately fails in FIrefox. 
I'm getting `TypeError: "'getComputedStyle' called on an object that does not implement interface Window."`

Full error:
~~~~
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408
TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408

    pa7React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408

    pa7React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

react-dom.production.min.js:4408

    pa7React

unstable_runWithPriority scheduler.production.min.js:274 Is12React

    q content.js:82 q content.js:73 

TypeError: "'getComputedStyle' called on an object that does not implement interface Window."

    exports computedStyle.commonjs.js:9 exports line-height.js:12 componentDidMount4React

unstable_runWithPriority scheduler.production.min.js:274 Is12React
q content.js:82 q content.js:73 ~~~~

**Comment by patrik-piskay** [comment]
Interesting @constantinpojoga. Can you create a repro example on https://codesandbox.io? Thanks!

**Comment by constantinpojoga** [comment]
I was not able to replicate that in code sandbox (
https://codesandbox.io/s/qz2klkq1w6), and unfortunately, I cannot share the
original code. I wonder if the environment is different in my case.

I'm working on a React extension, which is using the content script to add
extra content to some pages. The data comes from our API, and some fields
are HTML strings, to preserve original styling (include em, strong, sup,
sub tags). I'm passing that string to sanitize() and renderHTML().
Sometimes the content was doing exactly what I need, especially I love that
I can include custom ellipsis and have an "onAfterTruncate" function.
Unfortunately, it fails for me in Firefox.
Just adding <TruncateMarkup><span>test</span></TruncateMarkup> will make it
fail.
I had to convert `react-truncate-markup` to `react-dotdotdot` to make it
work, without any other changes.
Since I was not able to replicate the issue in codesandbox, I feel like you
may close this issue.

I really like your package and hope to use it with more luck on my next
project.

Thank you




On Fri, Mar 22, 2019 at 2:36 PM Patrik Piskay <notifications@github.com>
wrote:
>
> Interesting @constantinpojoga. Can you create a repro example on
https://codesandbox.io? Thanks!

**Comment by patrik-piskay** [comment]
I wonder what the `this.el` is assigned to here for you https://github.com/parsable/react-truncate-markup/blob/master/src/index.js#L132 - it should always be a DOM element, and we pass that DOM element to `window.getComputedStyle` function

Another way to bypass this is to set the `lineHeight` prop, that way we'll never call `getComputedStyle` - not sure whether that's an option for you or not.

Anyway, looks like you found a workaround and it _looks_ like an environment issue, so closing this
