### ISSUE TITLE
Enzyme test fails with "Invariant Violation: Element type is invalid error"

### ISSUE THREAD

**Issue by subs1da** [parsable/react-truncate-markup#24]
The below minimal enzyme test fails with error message "Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `WrapperComponent`.":

```
import { mount } from 'enzyme';
import * as React from 'react';
import Truncate from 'react-truncate-markup';

describe('truncate', () => {
  it('renders', () => {
    mount(<Truncate>foo</Truncate>);
  });
});
```

My project is in TypeScript (not sure if it matters?) and my dependencies:
- enzyme: 3.9.0
- enzyme-adapter-react-16: 1.11.2
- jest: 24.5.0
- jsdom-global: 3.0.2
- react: 16.8.5
- react-dom: 16.8.5
- react-truncate-markup: 3.0.1
- ts-jest: 24.0.0
- typescript: 3.3.4000
- @types/enzyme: 3.9.1
- @types/jest: 24.0.11
- @types/react: 16.8.8

**Comment by patrik-piskay** [comment]
Interesting. What I get when I run that code is `Invariant Violation: React.Children.only expected to receive a single React element child.` and a prop warning: `Warning: Failed prop type: Invalid prop 'children' of type 'string' supplied to 'TruncateMarkup', expected a single ReactElement.`

which points to this not being valid usage:
```
<Truncate>foo</Truncate>
```
`foo` needs to be wrapped in a container, i.e. `div`:
```
<Truncate><div>foo</div></Truncate>
```

**Comment by subs1da** [comment]
Interesting... Your point is fair, the example wasn't valid, but even the below causes the same error (note, my error is not the same as yours....):

```
mount(<Truncate><div>foo</div></Truncate>);
```

**Comment by patrik-piskay** [comment]
Can you create a repro case using codesanbox? it supports jest/enzyme tests, so hopefully you'll be able to reproduce it there.

**Comment by subs1da** [comment]
Codesandbox wouldn't actually run the test for some reason :confused: ... But here's a minimal example on github: https://github.com/subs1da/test-react-truncate-markup

**Comment by patrik-piskay** [comment]
So it still doesn't look like this library's issue - I managed to get the test running by removing `jsdom-global` from `setupTests.js` and `testEnvironment: 'node'` from `jest.config.js` (this can by changed to `testEnvironment: 'jsdom'` too)

**Comment by subs1da** [comment]
Thank you for having a look, I never would have thought of that... (WTH?!) I'll see if I can make the same change in my project (which is obviously slightly larger than the example I uploaded :weary:)

**Comment by subs1da** [comment]
OK, unfortunately the above doesn't fix it for me (and in my project, react-truncate-markup is the only component that does this in the tests) but I appreciate it's not this library's issue :(

**Comment by patrik-piskay** [comment]
so changing `testEnvironment: 'node'` to `testEnvironment: 'jsdom'` and removing `jsdom-global` call doesn't fix it?

I'll try to find some time to dig deeper, hoping I can find something that RTM does that causes this

**Comment by subs1da** [comment]
That's much appreciated. I have mocked RTM out of the tests for now (but with a heavy heart :))

**Comment by smesgr** [comment]
I can reproduce this issue too. I managed to get things going by removing
module.exports = exports['default'];
from lib/index.js
could you please have a look at this issue again?
