### ISSUE TITLE
TypeError: Cannot read property '_ownerDocument' of undefined

### ISSUE THREAD

**Issue by maxkordiyak** [parsable/react-truncate-markup#28]
Hi, anyone tried to use this library with Storybook?
I'm getting   
```
  TypeError: Cannot read property '_ownerDocument' of undefined
      at TruncateMarkup.componentDidMount (../../node_modules/react-truncate-markup/lib/index.js:171:73)
```
on each snapshot, even if their component do not `import TruncateText from react-truncate-markup`

**Comment by maxkordiyak** [comment]
I tried to mock out this library as described here https://github.com/facebook/react/issues/9244 but it doesn't work

**Comment by patrik-piskay** [comment]
Hi @maxkordiyak, sorry for the late response. We are not using storybook so I can't help much on this one. Have you done more debugging around it? From your report it looks like it originates in `componentDidMount` where 2 dependencies are used - `line-height` and `ResizeObserver` - maybe one of them is causing issues?

**Comment by remylenoir** [comment]
Hello, @maxkordiyak did you find what caused the issue? I am facing the same problem when I run the snapshot test, I am also using Storybook:

```TypeError: Cannot read property 'style' of null
 at TruncateMarkup.componentDidMount (node_modules/react-truncate-markup/lib/index.js:171:73)```

**Comment by remylenoir** [comment]
Thank you @maxkordiyak , it worked like a charm.

For other people using Storybook + Storyshots for snapshot testing, I put the mock code within my Storybook file:

```import { storiesOf } from '@storybook/react';  

jest.mock('react-truncate-markup/lib/index.js', () => {
  return (props: any) => <div>{props.children}</div>;
});  

storiesOf('My story', module)
  .add('All Sections', () => (
    <div>
      // Component using react-truncate-markup
    </div>
  ));
```
