### ISSUE TITLE
Doesnt work with JSX dangerouslySetInnerHTML attribute

### ISSUE THREAD

**Issue by thinkb4code** [parsable/react-truncate-markup#31]
I am using this control to trim rich text editor output html to 5 lines but not working. I am using JSX attribute dangerouslySetInnerHTML to set the HTML inside a div control. My HTML content is simply consist of divs and paragraph.

`<TruncateMarkup lines={6}>
						<div>  
							<div dangerouslySetInnerHTML={{__html: this.state.data.Body}}>
								</div>
						</div>
					</TruncateMarkup>`

This makes the entire react component go blank. Following is error on browser console.
`Invariant Violation: Minified React error #185;`

**Comment by patrik-piskay** [comment]
Do you mind creating a repro case using codesandbox.io where this exact case can be seen in action and debugged? Thanks

**Comment by Daninet** [comment]
Something similar:
https://codesandbox.io/s/truncatemarkup-demo-lvdmd?fontsize=14

**Comment by patrik-piskay** [comment]
Thanks @Daninet, actually now seeing this I realized that's not supported by design. Please see https://github.com/parsable/react-truncate-markup/issues/19#issuecomment-464221889 for explanation and a workaround suggestion. cc @thinkb4code
