### ISSUE TITLE
Feature Proposal: support components

### ISSUE THREAD

**Issue by stropho** [parsable/react-truncate-markup#48]
Hello, great library, useful for many common scenarios. After some time I have a need to extend the functionality in a way that we could use React components in `TruncateMarkup` .

**Common use case**: display a list of components, either created with react html markup or actual react (class/functional) components, and display only as many components as possibly - based on their size.
![image](https://user-images.githubusercontent.com/3704482/78108098-ff43bd80-73f6-11ea-8ecd-3022fac96614.png)

I understand there is no way how to possibly split react components. That's not my intention.

### Solution 1 - Atomic Elements
This option was already discussed in some older PR
```jsx
<TruncateMarkup>
  <div>
    <span truncateAtom>{ /* ... can have custom Components inside */ }</span>
    <span truncateAtom>{ /* ... can have more DOM nodes inside */ }</span>
   {/* or possibly with a custom component provided by this lib */}
    <TruncateMarkupAtom>{ /* ... can have custom Components inside */ }</TruncateMarkupAtom>
    <TruncateMarkupAtom>{ /* ... can have more DOM nodes inside */ }</TruncateMarkupAtom>
  </div>
</TruncateMarkup>
```
This seems to be a easy solution as long as there is good way to indicate that a element/Component should not be analyzed any further.
Props types stay the same thus it doesn't introduce breaking changes.

1.1 Is a component preferred over some custom prop? Or maybe let's just see what ever is easier to do..
1.2 In either way, I think we'll need to check children (=potential Atom) props - that doesn't sounds great, but to some extend that is already happening in the lib. Right now, I am not aware of a way how to easily and reliably check if a node is create by a specific React component. Or is there a way ?

### Solution 2 - New `tokenize` Option
a new `tokenize` option could be aslo a way, but the more I think about it, the more complex it is. Either to document what that option would and wouldn't do, or to provide multiple `tokenize` options for slightly different usecases. The complexity of the code handling these options would get just more complicated than it needs to be.

I am willing to do a PR. I'd like to reach some kind of agreement here before doing that so the time is well spent :smile:

**Comment by patrik-piskay** [comment]
@stropho I think this is a good idea! I'd definitely prefer the simplicity of providing a component like `TruncateMarkupAtom` 👍 there should be ways to easily and safely detect this component. checking `node.type === TruncateMarkupAtom` should work fine 🤞
