### ISSUE TITLE
Warning when used in tab

### ISSUE THREAD

**Issue by collaboration-tools** [parsable/react-truncate-markup#52]
Great little component - thanks. Your home page does discuss conditional rendering, but any advice on using the component in a TabContainer? Every time a tab not containing the component is selected, the warning below is triggered:

console.warn('ReactTruncateMarkup: number of currently rendered lines: ' + computedLines + ', not truncating...\n  It may be caused by target element not being visible at the time of computation.');

I've had to comment it out since in dev it clogs up the console ;-)

Best, Keith

**Comment by patrik-piskay** [comment]
Fixed in [v5.1.0](https://github.com/parsable/react-truncate-markup/releases/tag/5.1.0)
