### ISSUE TITLE
Fails to truncate when there is just one long string

### ISSUE THREAD

**Issue by abashir17** [parsable/react-truncate-markup#56]
**Describe the bug**
Hello,

I've noticed a bug where it fails to truncate at all when the string is a single long word. Add whitespace at any point and everything is fine though.

<img width="1181" alt="Screen Shot 2020-08-17 at 6 14 20 PM" src="https://user-images.githubusercontent.com/11590841/90450614-28b86980-e0b8-11ea-9237-429bd357b298.png">
<img width="1184" alt="Screen Shot 2020-08-17 at 6 13 57 PM" src="https://user-images.githubusercontent.com/11590841/90450644-30780e00-e0b8-11ea-854d-bec2b1230432.png">

**To Reproduce**
https://codesandbox.io/s/truncatemarkup-demo-forked-ys7f4?file=/index.js

**Comment by patrik-piskay** [comment]
Fixed in https://github.com/parsable/react-truncate-markup/releases/tag/5.1.0

**Comment by abashir17** [comment]
Awesome, thank you Patrik!
