### ISSUE TITLE
Typescript .d.ts is not pushed to npm 😢

### ISSUE THREAD

**Issue by burtek** [parsable/react-truncate-markup#6]
Please re-publish package with typescript declaration file included

**Comment by patrik-piskay** [comment]
Hey @burtek, version 1.1.0 with the typescript declarations file is already on npm 

https://github.com/parsable/react-truncate-markup/commits/1.1.0
https://www.npmjs.com/package/react-truncate-markup/v/1.1.0

**Comment by burtek** [comment]
The version 1.1.0 is on npm, but **without** .d.td. I guess you'd have to put `index.d.ts` in `package.json`'s `files` field or something, I don't know. But there are no typescript types in 1.1.0 npm package.

**Comment by patrik-piskay** [comment]
🤦‍♂️ you're right

**Comment by burtek** [comment]
:)
Apart from that - best truncate library for react I ever found :)

**Comment by burtek** [comment]
When can we expect this to go out? No hurry, we've put those typings in our `src/`, so just asking out of curiosity

**Comment by patrik-piskay** [comment]
Pushed now
