### ISSUE TITLE
Issue when content is number.

### ISSUE THREAD

**Issue by nikeshmhr** [parsable/react-truncate-markup#88]
**Describe the bug**
When the content to truncate is number an error occurs.

**To Reproduce**
```
<TruncateMarkup lines={1} ...>
  <div>
    {1}
  </div>
</TruncateMarkup>
```
Here's the code sandbox https://codesandbox.io/s/react-truncate-markup-issue-4xgwc?file=/src/App.js

![Screenshot from 2021-05-18 15-47-23](https://user-images.githubusercontent.com/7429948/118632748-72bdaf80-b7f0-11eb-86bd-f338313e7f0d.png)

**Comment by patrik-piskay** [comment]
Thanks for reporting @nikeshmhr. We need to check for the number type [here](https://github.com/parsable/react-truncate-markup/blob/master/src/index.js#L59). Would you like to create a PR with the fix?

**Comment by nikeshmhr** [comment]
Yeah, sure I'll create PR. Thanks @patrik-piskay
