### ISSUE TITLE
Suppressing console error logs

### ISSUE THREAD

**Issue by JustJelena** [parsable/react-truncate-markup#92]
Hi, 
I wonder if there is a way to suppress console error logs if React components are passed as children? I am happy with the scenario where there is not truncating if content contains React components. 
Thanks, 
Jelena

**Comment by patrik-piskay** [comment]
Hey Jelena, would using [Atoms](https://github.com/parsable/react-truncate-markup#truncatemarkupatom-) work for you, as suggested in the console error? By explicitly marking React components as TruncateMarkup Atoms, you won't get errors and truncation will work (which it won't at all with the error).

If TM atoms are not a feasible option for you, can you share your use case?

**Comment by JustJelena** [comment]
Hi Patrick, thanks for the prompt response! Yes now that I properly tried it out, it does work - it wasn't the most intuitive thing so I haven't picked it up properly from the docs, but it makes perfect sense. 
I was also thinking of rendering a 'dynamic' content that could be anything (e.g. a set of React components that the wrapper has no control of). 
For now though, Atoms will do. Thanks!

**Comment by JustJelena** [comment]
Hi Patrick, somewhat unrelated question (if you don't mind - happy to start another 'issue' if needed): if content is rendered with 
<span dangerouslySetInnerHTML={{ __html: htmlContentToRender }} />
there is no truncating of the content passed in the html string, is this to be expected? Thanks.

**Comment by patrik-piskay** [comment]
Yes, it's expected. RTM requires JSX tree as children to be functional, `dangerouslySetInnerHTML` bypasses that. 

Related https://github.com/parsable/react-truncate-markup/issues/19 with a possible workaround using something like `react-html-parser`

**Comment by JustJelena** [comment]
Thank you - I used htmr library as it's lighter and does the job.
