### ISSUE TITLE
Dosen't work with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Zanaxhir** [parsable/react-truncate-markup#99]
Dosen't work with

```
dangerouslySetInnerHTML={{
                    __html: props.text,
                }}
```

https://codesandbox.io/s/truncatemarkup-demo-forked-r9lhtp?file=/index.js

**Comment by patrik-piskay** [comment]
That's by design, but there is a [workaround](https://github.com/patrik-piskay/react-truncate-markup/issues/19#issuecomment-464221889) - transforming a html string into a React elements tree.
